URL = ''  # Mattermost Url
BOT_TOKEN = ''
BOT_NAME = ''
SCHEME = ''
PROJECT_ID = ''  # dialogflow project name
SESSION_ID = ''  # dialogflow client id
aws_access_key_id = ''
aws_secret_access_key = ''
region_name = ''
GITLAB_ACCESS_TOKEN = ''
CODESHIP_EMAIL = ''
CODESHIP_PASSWORD = ''
DB_URL = ''
DB_USER = ''
DB_PASSWORD = ''
DB_NAME = ''
DB_PORT = 3306
BASE_URL = ''  # at the end don't include "/"
GOOGLE_APPLICATION_CREDENTIALS = ''  # put path of json file
