# Generated by Django 3.0.2 on 2020-01-29 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200127_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('roles', models.CharField(max_length=250, null=True)),
                ('channel_id', models.CharField(max_length=250, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 1, 29, 19, 40, 19, 143129))),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='InsatnceAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='insatnceaccess',
            name='instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Instance'),
        ),
        migrations.AddField(
            model_name='insatnceaccess',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.BotUser'),
        ),
    ]
