# Generated by Django 3.0.2 on 2020-01-29 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200129_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsatnceAccess',
            new_name='InstanceAccess',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 19, 47, 6, 35756)),
        ),
    ]
