# Generated by Django 3.0.2 on 2020-01-29 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200129_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='roles',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 20, 11, 45, 379908)),
        ),
    ]
