# Generated by Django 3.0.2 on 2020-01-29 21:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200129_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 21, 45, 11, 670283)),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.BotUser'),
        ),
    ]
