# Generated by Django 3.0.2 on 2020-01-30 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200129_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='manager',
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 20, 22, 30, 767851)),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Instance')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.BotUser')),
            ],
        ),
    ]
