# Generated by Django 3.0.2 on 2020-01-30 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200130_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 20, 37, 11, 214518)),
        ),
        migrations.AlterField(
            model_name='instanceaccess',
            name='instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Instance'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Instance'),
        ),
    ]
