# Generated by Django 3.0.2 on 2020-01-31 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200130_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 22, 2, 21, 101650)),
        ),
        migrations.CreateModel(
            name='InstanceOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('channel_id', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('response_date', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 22, 2, 21, 103111))),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 1, 31, 22, 2, 21, 103125))),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_user', to='user.BotUser')),
                ('response_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='response_user', to='user.BotUser')),
            ],
        ),
    ]
