# Generated by Django 3.0.2 on 2020-01-31 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200131_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instanceoperation',
            old_name='request_user',
            new_name='requested_user',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 22, 5, 4, 783899)),
        ),
        migrations.AlterField(
            model_name='instanceoperation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 22, 5, 4, 785314)),
        ),
        migrations.AlterField(
            model_name='instanceoperation',
            name='response_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 22, 5, 4, 785301)),
        ),
    ]
