# Generated by Django 3.0.2 on 2020-02-03 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200131_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 13, 21, 23, 271379)),
        ),
        migrations.AlterField(
            model_name='instanceoperation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 13, 21, 23, 274332)),
        ),
        migrations.AlterField(
            model_name='instanceoperation',
            name='response_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='response_user', to='user.BotUser'),
        ),
        migrations.AlterField(
            model_name='instanceoperation',
            name='response_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 13, 21, 23, 274304), null=True),
        ),
    ]
